// types/index.ts - UPDATED
export interface User {
    _id?: string;
    email: string;
    password: string;
    createdAt?: Date;
}

// CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,BEGIN_DATE,END_DATE,TOTAL_WORKER_POSITIONS,NEW_EMPLOYMENT,CONTINUED_EMPLOYMENT,CHANGE_PREVIOUS_EMPLOYMENT,NEW_CONCURRENT_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,EMPLOYER_NAME,TRADE_NAME_DBA,EMPLOYER_ADDRESS1,EMPLOYER_ADDRESS2,EMPLOYER_CITY,EMPLOYER_STATE,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,EMPLOYER_PHONE_EXT,EMPLOYER_FEIN,NAICS_CODE,EMPLOYER_POC_LAST_NAME,EMPLOYER_POC_FIRST_NAME,EMPLOYER_POC_MIDDLE_NAME,EMPLOYER_POC_JOB_TITLE,EMPLOYER_POC_ADDRESS1,EMPLOYER_POC_ADDRESS2,EMPLOYER_POC_CITY,EMPLOYER_POC_STATE,EMPLOYER_POC_POSTAL_CODE,EMPLOYER_POC_COUNTRY,EMPLOYER_POC_PROVINCE,EMPLOYER_POC_PHONE,EMPLOYER_POC_PHONE_EXT,EMPLOYER_POC_EMAIL,AGENT_REPRESENTING_EMPLOYER,LAWFIRM_NAME_BUSINESS_NAME,STATE_OF_HIGHEST_COURT,NAME_OF_HIGHEST_STATE_COURT,WORKSITE_WORKERS,SECONDARY_ENTITY,SECONDARY_ENTITY_BUSINESS_NAME,WORKSITE_ADDRESS1,WORKSITE_ADDRESS2,WORKSITE_CITY,WORKSITE_COUNTY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,PREVAILING_WAGE,PW_UNIT_OF_PAY,PW_TRACKING_NUMBER,PW_WAGE_LEVEL,PW_OES_YEAR,PW_OTHER_SOURCE,PW_OTHER_YEAR,PW_SURVEY_PUBLISHER,PW_SURVEY_NAME,TOTAL_WORKSITE_LOCATIONS,AGREE_TO_LC_STATEMENT,H_1B_DEPENDENT,WILLFUL_VIOLATOR,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,JOB_DOMAIN,WAGE_NUMERIC,PREVAILING_WAGE_NUMERIC


export interface LCARecord {
    CASE_NUMBER: string;
    CASE_STATUS: string;
    RECEIVED_DATE?: string;
    DECISION_DATE?: string;
    VISA_CLASS?: string;
    EMPLOYER_NAME: string;
    JOB_TITLE: string;
    JOB_DOMAIN?: string;
    SOC_CODE?: string;
    SOC_TITLE: string;
    EMPLOYER_CITY: string;
    EMPLOYER_STATE: string;
    EMPLOYER_POSTAL_CODE?: string;
    WAGE_RATE_OF_PAY_FROM: string;
    WAGE_RATE_OF_PAY_TO?: string;
    WAGE_UNIT_OF_PAY?: string;
    PREVAILING_WAGE?: string;
    PW_UNIT_OF_PAY?: string;
    PW_WAGE_LEVEL?: string;
    FULL_TIME_POSITION?: string;
    BEGIN_DATE?: string;
    END_DATE?: string;
    NAICS_CODE?: string;
    H_1B_DEPENDENT?: string;
    WILLFUL_VIOLATOR?: string;
    TOTAL_WORKER_POSITIONS?: string;
    NEW_EMPLOYMENT?: string;
    CONTINUED_EMPLOYMENT?: string;
    CHANGE_PREVIOUS_EMPLOYMENT?: string;
    EMPLOYER_POC_EMAIL?: string;
    EMPLOYER_POC_FIRST_NAME?: string;
    EMPLOYER_POC_LAST_NAME?: string;
    EMPLOYER_POC_MIDDLE_NAME?: string;
    EMPLOYER_POC_JOB_TITLE?: string;
    EMPLOYER_POC_ADDRESS1?: string;
    EMPLOYER_POC_ADDRESS2?: string;
    EMPLOYER_POC_CITY?: string;
    EMPLOYER_POC_STATE?: string;
    EMPLOYER_POC_POSTAL_CODE?: string;
    EMPLOYER_POC_COUNTRY?: string;
    EMPLOYER_POC_PROVINCE?: string;
    EMPLOYER_POC_PHONE?: string;
    EMPLOYER_POC_PHONE_EXT?: string;
    AGENT_REPRESENTING_EMPLOYER?: string;
    LAWFIRM_NAME_BUSINESS_NAME?: string;
    STATE_OF_HIGHEST_COURT?: string;
    NAME_OF_HIGHEST_STATE_COURT?: string;
    WORKSITE_WORKERS?: string;
    SECONDARY_ENTITY?: string;
    SECONDARY_ENTITY_BUSINESS_NAME?: string;
    WORKSITE_ADDRESS1?: string;
    WORKSITE_ADDRESS2?: string;
    WORKSITE_COUNTY?: string;
    EMPLOYER_ADDRESS1?: string;
    EMPLOYER_PHONE?: string;
    WORKSITE_CITY?: string;
    WORKSITE_STATE?: string;
    WORKSITE_POSTAL_CODE?: string;
    [key: string]: any;
}

export interface FilterOption {
    column: string;
    values: string[];
}

export interface ApplicationTracking {
    _id?: string;
    userId: string;
    userEmail: string;
    companyName: string;
    jobTitle: string;
    employerDomain: string;
    recipientEmail: string;
    caseNumber?: string;
    emailSubject: string;
    emailBody: string;
    status: 'sent' | 'failed';
    sentAt: Date;
    lcaData?: Partial<LCARecord>;
}